#!/bin/bash
#
# Starts the server.
# The server tries to run on port PORT which is defined in config.h
# On default, it listens to all addresses.
# Otherwise, a specific address and port may be given as follows:
#
#         Syntax:  ```./server ADDRESS:PORT [OPTION]```
#
# [OPTION] may be either of:
#     	--license	Print the License and exit
#	--build		(Re-)build the project before execution
# 

build_dir="cmake-build-debug"

if test "$1" == "--license"
then cat LICENSE
exit
fi

mkdir $build_dir 2> /dev/zero
if test $? -eq 0 || test "$1" == "--build"
then ./setup/build $build_dir > "$build_dir/Debug $(date).log" 2> "$build_dir/Error $(date).log"
fi

export SCRATCHQL_ROOT=$PWD

echo "$0 $*"; echo "========"
cmd="./$build_dir/Database --server"

if test $# -gt 1
then cmd="$cmd $2"
elif test $# -gt 0 && test "$1" != "--build"
then cmd="$cmd $1"
fi
$cmd
