#!/bin/bash

# Build cmake cache
cmake -H. -Bcmake-build-debug

# Install Cap'n Proto:
VERSION="0.8.0"
curl -O "https://capnproto.org/capnproto-c++-$VERSION.tar.gz"
tar zxf "capnproto-c++-$VERSION.tar.gz"
cd "capnproto-c++-$VERSION" || exit 1
./configure
make -j6 check
sudo make install
cd ../
