#!/bin/bash

# Build cmake cache
cmake -H. -Bcmake-build-debug

# Install Cap'n Proto:
curl -O https://capnproto.org/capnproto-c++-0.7.0.tar.gz
tar zxf capnproto-c++-0.7.0.tar.gz
cd capnproto-c++-0.7.0 || exit 1
./configure
make -j6 check
sudo make install
cd ../
